### ISSUE TITLE
No field DEF_CONTENT_CHARSET of type Ljava/nio/charset/Charset;

### ISSUE THREAD

**Issue by nazarrrk0** [Nexmo/nexmo-java#130]
I get this error when using code from your documentation.

AuthMethod auth = new TokenAuthMethod(API_KEY, API_SECRET);
NexmoClient client = new NexmoClient(auth);
VerifyResult ongoingVerify = client.getVerifyClient().verify(TO_NUMBER, "NEXMO");

When this code is executed i get this error :
No field DEF_CONTENT_CHARSET of type Ljava/nio/charset/Charset;

Full error log:

java.lang.NoSuchFieldError: No field DEF_CONTENT_CHARSET of type Ljava/nio/charset/Charset; in class Lorg/apache/http/protocol/HTTP; or its superclasses (declaration of 'org.apache.http.protocol.HTTP' appears in /system/framework/org.apache.http.legacy.boot.jar)
                                                                       at org.apache.http.client.methods.RequestBuilder.build(RequestBuilder.java:483)
                                                                       at com.nexmo.client.voice.endpoints.AbstractMethod.execute(AbstractMethod.java:83)
                                                                       at com.nexmo.client.verify.endpoints.VerifyEndpoint.verify(VerifyEndpoint.java:100)
                                                                       at com.nexmo.client.verify.VerifyClient.verify(VerifyClient.java:82)
                                                                       at com.vismox.vismox.activities.SignUpActivity.onClick(SignUpActivity.java:341)
                                                                       at android.view.View.performClick(View.java:6261)
                                                                       at android.widget.TextView.performClick(TextView.java:11180)
                                                                       at android.view.View$PerformClick.run(View.java:23748)
                                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by judy2k** [comment]
Hi @nazarrrk0, I'm afraid we don't currently support Android, as distributing your Nexmo key and secret in in the app is a security risk. You need to build a server for this, and have your Android app call that.
