### ISSUE TITLE
NullPointerException thrown by the ModifyCallResponse.fromJson when input is null

### ISSUE THREAD

**Issue by nicolagiacchetta** [Nexmo/nexmo-java#137]
As shown in the following stack trace, a NullPointerException is thrown by the fromJson method of the ModifyCallResponse class when the input String has a null value.

`java.lang.NullPointerException: null
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:889) ~[jackson-core-2.9.2.jar:2.9.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992) ~[jackson-databind-2.9.2.jar:2.9.2]
	at com.nexmo.client.voice.ModifyCallResponse.fromJson(ModifyCallResponse.java:48) ~[client-3.2.0.jar:3.2.0]
	at com.nexmo.client.voice.endpoints.ModifyCallMethod.parseResponse(ModifyCallMethod.java:69) ~[client-3.2.0.jar:3.2.0]
	at com.nexmo.client.voice.endpoints.ModifyCallMethod.parseResponse(ModifyCallMethod.java:41) ~[client-3.2.0.jar:3.2.0]
	at com.nexmo.client.voice.endpoints.AbstractMethod.execute(AbstractMethod.java:107) ~[client-3.2.0.jar:3.2.0]
	at com.nexmo.client.voice.endpoints.CallsEndpoint.put(CallsEndpoint.java:100) ~[client-3.2.0.jar:3.2.0]
	at com.nexmo.client.voice.VoiceClient.modifyCall(VoiceClient.java:161) ~[client-3.2.0.jar:3.2.0]
	at com.nexmo.client.voice.VoiceClient.modifyCall(VoiceClient.java:146) ~[client-3.2.0.jar:3.2.0]`
  
The null value is returned after the following call is correctly executed:
`nexmoClient.getVoiceClient().modifyCall(uuid, ModifyCallAction.HANGUP);`

**Comment by judy2k** [comment]
Resolved in v3.3.0
