### ISSUE TITLE
com.nexmo.client.NexmoResponseParseException: No valid response found

### ISSUE THREAD

**Issue by newuni** [Nexmo/nexmo-java#144]
Situation

When invoking check method an exception is thrown in VerifyEndpoint.parseVerifyResponse if the number is not a valid number, I think a managed error should be returned as the raw content of the API call returns.

Code

```
AuthMethod auth = new TokenAuthMethod(ApiConstants.NEXMO_KEY, ApiConstants.NEXMO_SECRET);
NexmoClient client = new NexmoClient(auth);
VerifyResult verifyResult = client.getVerifyClient().verify(phone, "Wannads Wall");
```

Stacktrace:

`com.nexmo.client.NexmoResponseParseException: No valid response found [ <?xml version="1.0" encoding="UTF-8"?> <response> <status>3</status> <error_text>Invalid value for param: number</error_text> </response> ] at com.nexmo.client.verify.endpoints.VerifyEndpoint.parseVerifyResponse(VerifyEndpoint.java:151) at com.nexmo.client.verify.endpoints.VerifyEndpoint.parseResponse(VerifyEndpoint.java:107) at com.nexmo.client.verify.endpoints.VerifyEndpoint.parseResponse(VerifyEndpoint.java:44) at com.nexmo.client.voice.endpoints.AbstractMethod.execute(AbstractMethod.java:107) at com.nexmo.client.verify.endpoints.VerifyEndpoint.verify(VerifyEndpoint.java:113)`

Version

```
<dependency>
            <groupId>com.nexmo</groupId>
            <artifactId>client</artifactId>
            <version>3.3.0</version>
</dependency>
```

**Comment by judy2k** [comment]
Hi @newuni - you're absolutely correct, this should raise an exception, but not a `NexmoResponseParseException`.

I'll schedule this bug to be fixed. Thanks for the bug report!

**Comment by andidev** [comment]
Same here

**Comment by SdlasHeras** [comment]
same for me, when this will be fixed?
