### ISSUE TITLE
intermittent connection failure

### ISSUE THREAD

**Issue by lcarasco** [Nexmo/nexmo-java#178]
The exception below is intermittently thrown (Client API v 3.4.1)
Is this likely to be a genuine communications failure which should be monitored for and retried, or is there a possible issue with dead pooled connections? 

java.net.SocketException: Connection reset
       at java.net.SocketInputStream.read(SocketInputStream.java:189)
       at java.net.SocketInputStream.read(SocketInputStream.java:121)
       at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
       at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
       at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
       at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
       at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
       at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
       at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
       at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
       at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
       at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
       at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
       at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
       at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
       at com.nexmo.client.voice.endpoints.AbstractMethod.execute(AbstractMethod.java:106)
       at com.nexmo.client.sms.SmsClient.submitMessage(SmsClient.java:73)

**Comment by cr0wst** [comment]
Hi @lcarasco,

What version of Java are you running?

**Comment by lcarasco** [comment]
OpenJDK 1.7.0 (with Tomcat 7.0.29)

**Comment by cr0wst** [comment]
Hi @lcarasco,

We are currently in the process of ending support for TLSv1.0. This process is outlined in the following article: https://www.nexmo.com/blog/2018/06/13/nexmo-protects-customers-by-ending-support-for-legacy-tls-protocols/

As outlined in the blog post:
> We will disable legacy TLS protocols in two stages:
>
> 1. July 10, 10:00 BST: Disable TLSv1 and TLSv1.1 for one hour (to facilitate detection of legacy API clients).
> 2. August 7, 10:00 BST: Permanently disable legacy TLSv1 and TLSv1.1.
> After the initial one-hour shutdown on 10th of July, we will temporarily restore support for TLSv1 and TLSv1.1 for a period of four weeks in order to mitigate adverse impact to your business and assist with your transition.

My assumption is that you received this exception during the timeframe in which TLSv1.0 and TLSv1.1 was disabled. If this is not the case, please let me know.

You can check to see if your version of Java supports TLSv1.2 by running the following code (depends on `HttpClient` from `org.apache.httpcomponents:httpclient`.

```java
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.HttpClientBuilder;

import java.io.IOException;

public class CheckTls {
    public static void main(String... args) throws IOException {
        boolean success = (HttpClientBuilder.create()
                .build()
                .execute(new HttpGet("https://api.nexmo.com/tlsverification"))
                .getStatusLine()
                .getStatusCode() == 200);
        System.out.println("Successful Response: " + success);
    }
}
```

The article mentions that Java 7 will be supported but you must be running a new enough version. The client will automatically select TLSv1.2 if you are running on 7u131 or newer. 

If you are unable to update your version of Java, you may have some success forcing the client to use TLSv1.2 but it requires you to be on at least 7u95. There is a property `jdk.tls.client.protocols` which can be used to enable TLSv1.2.  More information can be found here: https://docs.oracle.com/javase/7/docs/technotes/guides/security/jsse/JSSERefGuide.html#Customization

**Comment by lcarasco** [comment]
Thanks @cr0wst, looks like this was the problem.
I wasn't aware TLSv1.0 support was ending.
