### ISSUE TITLE
Supported cipher suites

### ISSUE THREAD

**Issue by sobryan** [Nexmo/nexmo-java#181]
After the cutover to TLS1.2, we see one cipher suite from nexmo during a handshake:
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

A wireshark capture of the handshake shows we have many TLS 1.2 ciphers (68 TLS_* )available in the java installation, this is not one. 

Please offer more than one cipher. 

The full stack trace is not helpful, other than saying "Unable to make a connection with IBM java"
java.net.SocketException: A system call received a parameter that is not valid. (Read failed)
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:127)
        at java.net.SocketInputStream.read(SocketInputStream.java:182)
        at java.net.SocketInputStream.read(SocketInputStream.java:152)
        at com.ibm.jsse2.b.a(b.java:254)
        at com.ibm.jsse2.b.a(b.java:121)
        at com.ibm.jsse2.at.a(at.java:462)
        at com.ibm.jsse2.at.i(at.java:73)
        at com.ibm.jsse2.at.a(at.java:357)
        at com.ibm.jsse2.at.startHandshake(at.java:723)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
        at com.nexmo.client.voice.endpoints.AbstractMethod.execute(AbstractMethod.java:106)
        at com.nexmo.client.sms.SmsClient.submitMessage(SmsClient.java:75)

**To add support for the cipher:**
Download bcprov-ext-jdk15on-{version}.jar and bctls-jdk15on-{version}.jar
https://mvnrepository.com/artifact/org.bouncycastle/bcprov-ext-jdk15on
https://mvnrepository.com/artifact/org.bouncycastle/bctls-jdk15on
Place the two files into your java installation: JAVA_HOME/jre/lib/ext
Edit the file JAVA_HOME/jre/lib/security/java.security
Look for the "security.provider" section
Above all the other "security.provider" lines add:
security.provider.1=org.bouncycastle.jce.provider.BouncyCastleProvider
security.provider.2=org.bouncycastle.jsse.provider.BouncyCastleJsseProvider
Change the numbers on the other providers

Thank you!

**Comment by cr0wst** [comment]
Hi @sobryan 

This repository is specifically for our Java Client Library. It looks like this is something that would require a change in our infrastructure/API.  I will reach out to our internal development team and pass along this issue.

Thanks!
Steve
