### ISSUE TITLE
NexmoUnexpectedException on calling InsightClient.getAdvancedNumberInsight() for landline

### ISSUE THREAD

**Issue by dmitryshirkalin** [Nexmo/nexmo-java#186]
Nexmo Java client version 3.7.0

The InsightClient.getAdvancedNumberInsight(phoneNumber) method calls fails on some landline numbers, when the server API responses with "valid_number": "inferred_not_valid".

For some landline numbers, for example 15810523625, the API JSON response contain the field "valid_number": "inferred_not_valid".
However the client enum com.nexmo.client.insight.advanced.AdvancedInsightResponse.Validity does not have the corresponding value, which causes JSON InvalidDefinitionException in parsing the response.

Error call stack:
com.nexmo.client.NexmoUnexpectedException: Failed to produce AdvancedInsightResponse from json.
at com.nexmo.client.insight.advanced.AdvancedInsightResponse.fromJson(AdvancedInsightResponse.java:54)
at com.nexmo.client.insight.advanced.AdvancedInsightEndpoint.parseResponse(AdvancedInsightEndpoint.java:70)
at com.nexmo.client.insight.advanced.AdvancedInsightEndpoint.parseResponse(AdvancedInsightEndpoint.java:36)
at com.nexmo.client.voice.endpoints.AbstractMethod.execute(AbstractMethod.java:108)
at com.nexmo.client.insight.InsightClient.getAdvancedNumberInsight(InsightClient.java:83)
...
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.nexmo.client.insight.advanced.AdvancedInsightResponse$Validity`, problem: No enum constant com.nexmo.client.insight.advanced.AdvancedInsightResponse.Validity.INFERRED_NOT_VALID
...
Caused by: java.lang.IllegalArgumentException: No enum constant com.nexmo.client.insight.advanced.AdvancedInsightResponse.Validity.INFERRED_NOT_VALID
at java.lang.Enum.valueOf(Enum.java:238)
at com.nexmo.client.insight.advanced.AdvancedInsightResponse$Validity.valueOf(AdvancedInsightResponse.java:120)
at com.nexmo.client.insight.advanced.AdvancedInsightResponse$Validity.fromString(AdvancedInsightResponse.java:127)

**Comment by cr0wst** [comment]
Hi @dmitryshirkalin,

I completely agree on both points that our enums should not only be updated to support all possible fields but should also include a fallback in case we're unable to deserialize a field.

Thanks for the report, I'll get to work on fixing this!

**Comment by cr0wst** [comment]
This is resolved with v3.8.0.
