### ISSUE TITLE
Can not generate JWT ??

### ISSUE THREAD

**Issue by SevrainChea** [Nexmo/nexmo-java#270]
Hi, 

I am using the java client for Voice API
I am trying to make a simple call to a phone number using my nexmo Number and I get this error from JwtGenerator :

java.lang.NoSuchMethodError: io.jsonwebtoken.JwtBuilder.addClaims(Ljava/util/Map;)Lio/jsonwebtoken/JwtBuilder;
	at com.nexmo.jwt.JwtGenerator.generate(JwtGenerator.kt:44)
	at com.nexmo.jwt.Jwt.generate(Jwt.kt:44)
	at com.nexmo.jwt.Jwt.generate$default(Jwt.kt:43)
	at com.nexmo.jwt.Jwt.generate(Jwt.kt)
	at com.nexmo.client.auth.JWTAuthMethod.apply(JWTAuthMethod.java:49)
	at com.nexmo.client.AbstractMethod.applyAuth(AbstractMethod.java:123)
	at com.nexmo.client.AbstractMethod.execute(AbstractMethod.java:78)
	at com.nexmo.client.voice.CallsEndpoint.post(CallsEndpoint.java:62)
	at com.nexmo.client.voice.VoiceClient.createCall(VoiceClient.java:65)
	at com.cegedim.docavenue.backend.service.nexmo.NexmoService.createCall(NexmoService.java:42)
	at com.cegedim.docavenue.backend.service.NexmoServiceTest.test(NexmoServiceTest.java:22)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)

Indeed, the jwt builder has no addClaimS method, only addClaim
Do i need to import an external JWT library to make it work ??

**Comment by slorello89** [comment]
@SevrainChea Looking at the community slack it looks like you were able to resolve this issue by upgrading your JWT dependency from 0.6.0 -> 0.10.5 api+impl+jackson so I'm going to close out this issue.
