### ISSUE TITLE
Missing values in CallStatus?

### ISSUE THREAD

**Issue by stefano-DM** [Nexmo/nexmo-java#68]
Hi,

How come  the `CallStatus` class does not contain values like `BUSY`, `FAILED`, `UNANSWERED`, `TIMEOUT`, `REJECTED`?

Calling `getCallDetails` on an call with `status : busy` will result in an error:
```
com.nexmo.client.NexmoUnexpectedException: Failed to produce json from CallInfo object.
	at com.nexmo.client.voice.CallInfo.fromJson(CallInfo.java:182)
	at com.nexmo.client.voice.endpoints.ReadCallMethod.parseResponse(ReadCallMethod.java:62)
	at com.nexmo.client.voice.endpoints.ReadCallMethod.parseResponse(ReadCallMethod.java:36)
	at com.nexmo.client.voice.endpoints.AbstractMethod.execute(AbstractMethod.java:107)
	at com.nexmo.client.voice.endpoints.CallsEndpoint.get(CallsEndpoint.java:88)
	at com.nexmo.client.voice.VoiceClient.getCallDetails(VoiceClient.java:108)
	at lu.test.actions.TestAction.events(TestAction.java:323)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
...
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:453)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:460)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:293)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:319)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:311)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:457)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.nexmo.client.voice.CallStatus, problem: No enum constant com.nexmo.client.voice.CallStatus.BUSY
 at [Source: {"uuid":"1ee08cfb-4f49-4882-b028-e450ac7cc758","status":"busy","direction":"outbound","rate":"0","price":"0.00000000","duration":"0","network":"27001","conversation_uuid":"CON-358257a8-7033-4d81-b2c8-ff3a1c54cc4b","to":{"type":"phone","number":"********"},"from":{"type":"phone","number":"********"},"_links":{"self":{"href":"/v1/calls/1ee08cfb-4f49-4882-b028-e450ac7cc758"}}}; line: 1, column: 57] (through reference chain: com.nexmo.client.voice.CallInfo["status"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:277)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1441)
	at com.fasterxml.jackson.databind.DeserializationContext.handleInstantiationProblem(DeserializationContext.java:1055)
	at com.fasterxml.jackson.databind.deser.std.FactoryBasedEnumDeserializer.deserialize(FactoryBasedEnumDeserializer.java:136)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842)
	at com.nexmo.client.voice.CallInfo.fromJson(CallInfo.java:180)
	... 129 more
Caused by: java.lang.IllegalArgumentException: No enum constant com.nexmo.client.voice.CallStatus.BUSY
	at java.lang.Enum.valueOf(Enum.java:236)
	at com.nexmo.client.voice.CallStatus.valueOf(CallStatus.java:27)
	at com.nexmo.client.voice.CallStatus.fromString(CallStatus.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:42)
	at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.callOnWith(AnnotatedMethod.java:130)
	at com.fasterxml.jackson.databind.deser.std.FactoryBasedEnumDeserializer.deserialize(FactoryBasedEnumDeserializer.java:133)
```
Thanks

**Comment by judy2k** [comment]
This was released in v2.1.0
